### ISSUE TITLE
Fail to import with sass-loader

### ISSUE THREAD

**Issue by perqin** [pgbross/vue-material-adapter#102]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

vue-material-adapter is still under active development. You can see our current progress on [master](https://github.com/pgbross/vue-material-adapter/tree/master).

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What vue-material-adapter Version are you using?

> 0.12.1

### What browser(s) is this bug affecting?

> Chrome Version 78.0.3904.97 (Official Build) (64-bit)

### What OS are you using?

> Arch Linux

### What are the steps to reproduce the bug?

> 1. Create a vue project with vue-cli v4
> 2. Follow the **Webpack/Rollup** section in [Getting started](https://pgbross.github.io/vue-material-adapter/#/docs/getting-started) instruction
> 3. In theme.scss, import the styles with `@import "~vue-material-adapter/style";`

### What is the expected behavior?

> Work fine.

### What is the actual behavior?

> The theme.scss doesn't compile:

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
7 │ @import "~vue-material-adapter/style";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /home/perqin/Workspaces/yukiri/yukiri-im-web/src/theme.scss 7:9  root stylesheet

 @ ./src/theme.scss 4:14-216 14:3-18:5 15:22-224
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.50.8:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

### Any other information you believe would be useful?

I've explored the `node_modules/vue-material-adapter/` directory but no any styles.* found:

```
$ ls node_modules/vue-material-adapter
dist  index.js  index.scss  LICENSE  package.json  README.md
```

**Comment by pgbross** [comment]
Thank you for your feedback, I will look into it as soon as I can. There was a major release of material-components-web recently with several breaking changes, so that is taking my attention at the moment.

However I wonder if the getting started docs have got out of date. When I import the styles into a web app I use something  like the following which shows it is possible to mix and match the exports from the individual components as well as using the styles directly from the `@material` library. In practice 
`@mcwv/button/index.scss` is a convenience as it simply is a reexport of `@material/button/mdc-button`. This library tries not to add any additional styles as it tries to avoid introducing additional behaviours or dependencies:

```
@import '@mcwv/button/index.scss';
@import '@mcwv/card/index.scss';
@import '@mcwv/checkbox/index.scss';
@import '@mcwv/dialog/index.scss';
@import '@mcwv/drawer/index.scss';
@import '@mcwv/fab/index.scss';
@import '@mcwv/floating-label/index.scss';
@import '@material/form-field/mdc-form-field';
@import '@mcwv/icon-button/index.scss';
@import '@mcwv/layout-grid/index.scss';
@import '@mcwv/linear-progress/index.scss';
@import '@mcwv/line-ripple/index.scss';
@import '@mcwv/list/index.scss';
@import '@mcwv/menu/index.scss';
@import '@material/menu-surface/mdc-menu-surface';
@import '@mcwv/radio/index.scss';
@import '@mcwv/ripple/index.scss';
@import '@mcwv/select/index.scss';
@import '@mcwv/snackbar/index.scss';
@import '@mcwv/tabs/index.scss';
@import '@mcwv/textfield/index.scss';
@import '@mcwv/top-app-bar/index.scss';
@import '@mcwv/typography/index.scss';
@import '@material/theme/mdc-theme';

```

that is used by a `webpack.config.js`

with the following test to match .scss files.

```
 {
          test: /\.scss$/,
          exclude: /\.module.(s(a|c)ss)$/,
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader?-url',
            },
            {
              loader: 'postcss-loader',
              options: {
                config: { path: __dirname + '/postss.config.js' },
              },
            },
            {
              loader: 'sass-loader',
              options: {
                sassOptions: {
                  includePaths: ['node_modules'],

                  fiber: true,
                },
              },
            },
          ],
        },
```


Hope that helps for now, and I will try and get the docs in better shape.

**Comment by perqin** [comment]
I created a fresh new Vue project, and it worked. Sadly, I can't make my original project work, even that I've copied all changes. Since there're not too many commits on my original project, I'm working on the new one now. I'll try to re-setup the project after the documentation is updated some day. Thanks you for your efforts on this library!

**Comment by perqin** [comment]
For reference, here's my working demo setup: [https://github.com/perqin/vue-material-adapter-demo](https://github.com/perqin/vue-material-adapter-demo).

**Comment by pgbross** [comment]
Isn't the equivalent import (compared to your demo) for pulling all the styles going to be:

```css
@import '~vue-material-adapter/index.scss';
```
I find in practice however that importing that full scss is not used in real applications as generally the app only needs a subset, so customizing which styles to import like your theme.scss in the demo is ideal.

There is also an example of a basic webpack setup in the new examples folder.
