### ISSUE TITLE
[Request] Add typescript declaration files

### ISSUE THREAD

**Issue by ftsell** [pgbross/vue-material-adapter#114]
It would be very helpful to have this plugin importable from typescript code

**Comment by JacobBlana** [comment]
Any new information. Would be sweet to have it working.

**Comment by pgbross** [comment]
Hi, I haven't had any offers of help so it is still on my list of things to do...

**Comment by pgbross** [comment]
I have added typescript types and a couple of examples in the next version of `vue-material-adapter` (`install with npm install vue-material-adapter@next`)

Hopefully that will allow you to experiment with this library.
