### ISSUE TITLE
Support for vue 3 #12

### ISSUE THREAD

**Issue by leibale** [pgbross/vue-material-adapter#170]
Hi,

What's the plan regarding support for Vue 3?

Thanks

**Comment by lexiboi** [comment]
i'll create a branch and try to get the 'basic-vue-cli' example running in Vue 3.

**Comment by lexiboi** [comment]
After a couple of hours reading the Code i think migrating this project to work with vue 3 might not be possible right now. 

Not all dependencies support vue3 yet. for instance:
The project is bundled with rollup, which uses the component-compiler-utils which do not support vue3 yet. 

so i think the best thing to do is either wait or write a material wrapper for vue 3 from scratch.

i might be completely wrong.

**Comment by pgbross** [comment]
Hi,

I am working on the conversion to Vue 3 but there are some structural changes needed, not least because $listeners, $attrs, and componentInstances have all changed.

**Comment by pgbross** [comment]
There is a beta version that uses `Vue -3` available in the `v-next` branch and can be installed with `npm install vue-material-adapter@next`. (it also uses `material-components-web v8`)

So far it is the existing components updated to handle the changes required by the two underlying libraries. It will be updated to add the new `material-components-web` components in due course.

**Comment by jfrag** [comment]
Hi,

Thank you for your hard and awesome work !
I get an error when i try to user esm version.
I put this on my html heaser:
`<script type="module" src="/node_modules/vue/dist/vue.esm-browser.js"></script>
<script type="module" src="/node_modules/vue-material-adapter/dist/vue-material-adapter.esm.js"></script>`

But i get this error:
`Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".`

No error line...

I don't know how to debug a js module...

**Comment by besingamkb** [comment]
hi im trying the vue3 with vue-material-adapter@next but its not working on my end.

![Screenshot from 2020-12-04 00-41-11](https://user-images.githubusercontent.com/6380139/101059618-71455580-35c9-11eb-9cfa-844af5cfefdc.png)

**Comment by pgbross** [comment]
Looks like there is a peer dependency there for the old version of vue - it must have been left over from the previous version and I haven't had that issue (I am using it in Node 15 with NPM 6.14.9). When I use npm v7 I get the same error - presumably because the latest npm tries to install peer dependencies when earlier versions left it up to the user.

I will updatre the old peer dependency and make a new build to see if that fixes things.

**Comment by pgbross** [comment]
Ok the latest version (1.0.0-beta.13) now installs for me when using npm >=v7.
