### ISSUE TITLE
Upgrade material-components-web from 7.0.0 to 8.0.0

### ISSUE THREAD

**Issue by klyakh** [pgbross/vue-material-adapter#171]
Any plans on upgrading to the newest MDC Web?

**Comment by pgbross** [comment]
The next version is being worked on and uses the latest `material-components-web (v8)` and `Vue 3`. There is a beta version (has the existing components updated for use with v8, but doesn't yet have the new components added in v8) available in the `v-next` branch. It can be experimented by installing with `npm install vue-material-adapter@next`.
