### ISSUE TITLE
Sticking drawer

### ISSUE THREAD

**Issue by simultsop** [pgbross/vue-material-adapter#172]
vue-material-adapter is still under active development. You can see our current progress on [master](https://github.com/pgbross/vue-material-adapter/tree/master).

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What vue-material-adapter Version are you using?

vue-material-adapter: 1.0.0

### What browser(s) is this bug affecting?
Chrome 88

### What OS are you using?
Ubuntu 20

### What are the steps to reproduce the bug?
When using drawer it listens when you click out of it and toggles it hence closes.

### What is the expected behavior?
Provide prop to stop auto hiding.

### What is the actual behavior?
No props.

**Comment by pgbross** [comment]
Apologies, there is a property "dimissible" that makes the drawer stay open until you dismiss it, but I see it is missing from the demo documentation.

Will update the demo documents next time.


e.g.
```html
 <mcw-drawer
        ref="drawer"
        v-model="open"
        dismissible
        class="primary-drawer"
      >
<!-- drawer contents/items here -->
</mcw-drawer>
```
as opposed to the "modal" version
```html
 <mcw-drawer
        ref="drawer"
        v-model="open"
        modal
        class="primary-drawer"
      >
<!-- drawer contents/items here -->
</mcw-drawer>
```

**Comment by simultsop** [comment]
Actually I was using modal and needed dismiss function, in fact it is in documentation but I tried the opposite set :dismissable="false"  like trying to make it stick there.

Thanks a lot for the prompt response.

**Comment by simultsop** [comment]
> Actually I was using modal and needed dismiss function, in fact it is in documentation but I tried the opposite set :dismissable="false" like trying to make it stick there.
> 
> Thanks a lot for the prompt response.

Additionally there's an error being logged whenever clicking anywhere else once dismissable prop is set:

Uncaught TypeError: foundation.handleScrimClick is not a function
 at Proxy.handleScrimClick2 (vue-material-adapter.esm.js:3174)
    at _ctx.modal._ctx.modal.createBlock.onClick._cache.<computed>._cache.<computed> (vue-material-adapter.esm.js:3365)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js:301)

@ | runtime-dom.esm-bundler.js:301
-- | --

Maybe worth mentioning I'm using it on a project using vue/vite as dev tool.

**Comment by pgbross** [comment]
I will look into that error - thanks
