### ISSUE TITLE
(Feature request) Enhanced Select

### ISSUE THREAD

**Issue by lucasmsegurado** [pgbross/vue-material-adapter#48]
Provide tools to create an Enhanced Select following this specifications https://material-components.github.io/material-components-web-catalog/#/component/select:

From already thank you very much

**Comment by pgbross** [comment]
Thank you for the request, it is on the list of features to add.

**Comment by pgbross** [comment]
`material-web-components` is changing the select element to only be the enhanced select, so I have been tracking the progress of the changes. I hope to work on the enhanced select soon.

**Comment by pgbross** [comment]
Included in v0.13.0
