### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by veonua** [pgbross/vue-material-adapter#52]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

vue-material-adapter is still under active development. You can see our current progress on [master](https://github.com/pgbross/vue-material-adapter/tree/master).

## Bugs

ERROR  Failed to compile with 25 errors                                                                                                                                                         4:01:25 PM

 error  in ./node_modules/@mcwv/tabs/tab.js

Module parse failed: Unexpected token (125:21)
You may need an appropriate loader to handle this file type.
|           'i',
|           {
|             class: { ... this.hasIcon.classes, 'mdc-tab__icon': 1 },
|             attrs: { tabindex: '0', 'aria-hidden': 'true' },
|             ref: 'icon',

 @ ./node_modules/@mcwv/tabs/index.js 6:0-30
 @ ./node_modules/vue-material-adapter/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

### What vue-material-adapter Version are you using?

"vue-material-adapter": "^0.8.0"

**Comment by matthenning** [comment]
Did you ever manage to fix this problem @veonua ?

**Comment by pgbross** [comment]
There is a `basic-webpack` application in the examples folder that demonstrates a possible webpack configuration that compiles. I tried adding a tab-bar to verify and it behaved correctly.
