### ISSUE TITLE
Documentantion for the Drawer component is outdated

### ISSUE THREAD

**Issue by Shaxine** [pgbross/vue-material-adapter#86]
The documentantion for the Drawer component is outdated, its mentioning the `mcw-layout-app` component (which I can't find anywhere) and it looks like the `toggle-drawer` event doesn't exist.

I'm coming from `vue-mdc-adapter` and I was expecting a smooth transaction, but it seems that a lot of things work differently.

**Comment by pgbross** [comment]
I have tried to keep functionality similar where possible, but the underlying `material-web-components` has changed a lot during its development so there are inevitably clashes. Previously it was hoped that elements like `mdc-layout-app` would be a useful enhancement, but is not actually something provided by the `material-web-components` library so is probably better not in a general purpose adapter library.

I will update the drawer documentation so at least it is accurate.

**Comment by pgbross** [comment]
Improved example in demo.
