### ISSUE TITLE
Menu Divider is rendered instead of Menu Item

### ISSUE THREAD

**Issue by nerg4l** [pgbross/vue-material-adapter#87]
### What vue-material-adapter Version are you using?

0.11.3

### What browser(s) is this bug affecting?

All

### What OS are you using?

Windows 10

### What are the steps to reproduce the bug?

- Create a Menu according to demo.
- `mcw-menu-divider` creates a `Unknown custom element` error
- `mcw-menu-item` renders a Menu Divider

### What is the expected behavior?

A Menu Item should be visible.

### What is the actual behavior?

A Menu Divider is rendered.

### Any other information you believe would be useful?

In `packages/mcwv-menu/menu-item.js` code for Menu Divider can be found.

**Comment by pgbross** [comment]
Thank you for the report, it certainly looks like it is incorrect. I will review the current behaviour of the underlying material-web-components and get a fix shortly.

**Comment by pgbross** [comment]
Following the BREAKING CHANGE in how lists (and therefore menus and selects) are structured from v0.14.0, the menu-divider helper component is not needed, instead include the following: 

```html
<mcw-list-divider></mcw-list-divider>
```

or just the html directly

```html
 <li class="mdc-list-divider" role="separator"></li>
```
